name: CI/CD Pipeline for Vintage

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./client 
          file: ./client/Dockerfile 
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/vintage:client

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./server 
          file: ./server/Dockerfile 
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/vintage:server
       
  deploy-to-ec2:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: build-and-push # This job runs only if build-and-push is successful

    steps:
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v1.2.1 
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22 
          script: |
            set -e # Exit immediately if a command exits with a non-zero status.
            echo "Navigating to app directory ${{ secrets.EC2_APP_PATH }}"
            cd ${{ secrets.EC2_APP_PATH }}
      
            echo "Pulling latest Docker images..."
            docker compose pull frontend backend 

            echo "Restarting Docker Compose services..."
            docker compose up -d --force-recreate frontend backend nginx certbot

            echo "Cleaning up old Docker images and containers..."
            docker image prune -af  true 
            docker container prune -f  true 

            echo "Deployment successful!"
